version: 2

sources:
  - name: staging
    database: retaildataanalysis
    schema: connecticut_rs

    tables:
      - name: real_state_sales

models:
  - name: real_state_sales
    description: ""
    columns:
      - name: serial_number
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
        


