version: 2

models:
  - name: facts_rs
    description: ""
    columns:
      - name: real_estate_id
        data_type: string
        description: ""

      - name: serial_number
        data_type: string
        description: ""

      - name: list_year
        data_type: int64
        description: ""

      - name: date_recorded
        data_type: datetime
        description: ""

      - name: town
        data_type: string
        description: ""

      - name: address
        data_type: string
        description: ""

      - name: assessed_value
        data_type: float64
        description: ""

      - name: sale_amount
        data_type: float64
        description: ""

      - name: sales_ratio
        data_type: float64
        description: ""

      - name: appraisal_value_cat
        data_type: string
        description: ""

      - name: property_type
        data_type: string
        description: ""

      - name: residential_type
        data_type: string
        description: ""

      - name: rn
        data_type: int64
        description: ""

      - name: state
        data_type: string
        description: ""

  - name: aggregates
    description: ""
    columns:
      - name: sales_per_year
        data_type: float64
        description: "The total sales per year and dissagregated by town"

      - name: deals_per_year
        data_type: int64
        description: "The total deals per year and town"
